# Generated by Django 4.0 on 2025-03-16 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_txt', models.CharField(max_length=500)),
                ('translated_txt', models.CharField(max_length=500)),
                ('original_audio', models.URLField()),
                ('traslated_audio', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[('hard', 'hard'), ('medium', 'medium'), ('easy', 'easy')])),
                ('prev_status', models.IntegerField(choices=[('hard', 'hard'), ('medium', 'medium'), ('easy', 'easy')])),
                ('next_Revision_Date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.DeleteModel(
            name='cards',
        ),
    ]
