# Generated by Django 4.0 on 2025-03-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_translation_delete_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='prev_status',
            field=models.CharField(choices=[('hard', 'hard'), ('medium', 'medium'), ('easy', 'easy')], max_length=6),
        ),
        migrations.AlterField(
            model_name='translation',
            name='status',
            field=models.CharField(choices=[('hard', 'hard'), ('medium', 'medium'), ('easy', 'easy')], max_length=6),
        ),
    ]
