# Generated by Django 4.0 on 2025-03-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_translation_prev_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='next_Revision_Date',
            new_name='next_revision_date',
        ),
        migrations.AlterField(
            model_name='translation',
            name='original_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/original'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='traslated_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/translated'),
        ),
    ]
