# Generated by Django 4.0 on 2025-03-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_translation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='traslated_audio',
            new_name='translated_audio',
        ),
    ]
